# Generated by Django 5.2.7 on 2025-10-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_social", models.CharField(max_length=255)),
                ("profession", models.CharField(max_length=150)),
                ("address", models.TextField(blank=True)),
                ("contact", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
