name: Deploy Prod to Elastic Beanstalk

on:
  push:
    branches:
      - main

env:
  REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  EB_APP: ${{ secrets.EB_APP_NAME }}
  EB_ENV: ${{ secrets.EB_ENV_PROD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Record previous version
        id: prev_version
        run: |
          PREV_VERSION=$(aws elasticbeanstalk describe-environments \
            --environment-names $EB_ENV \
            --query "Environments[0].VersionLabel" \
            --output text)
          echo "PREV_VERSION=$PREV_VERSION" >> $GITHUB_ENV
        
      - name: Generate version label
        run: echo "VERSION_LABEL=v-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Generate deployment package
        run: |
          zip -r deploy-${{ github.run_id }}.zip . -x "*.git*" 
      
      # - name: 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          application_name: ${{ env.EB_APP }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          environment_name: ${{ env.EB_ENV }}
          version_label: v-${{ github.run_id }}
          region: ${{ env.REGION }}
          deployment_package: deploy-${{ github.run_id }}.zip
          wait_for_environment_recovery: 60

      - name: Rollback if deploy fails
        if: failure()
        run: |
          echo "Deploy failed, initiating rollback..."
          if [ "$PREV_VERSION" != "null" ] && [ "$PREV_VERSION" != "None" ] && [ -n "$PREV_VERSION" ]; then
          echo "Rolling back to previous version: $PREV_VERSION"
          aws elasticbeanstalk update-environment \
            --environment-name $EB_ENV \
            --version-label $PREV_VERSION
          echo "Rollback completed for $PREV_VERSION!"
            else
          echo "This is the first deployment, no previous version to rollback to."
          echo "Manual intervention may be required."
            fi
